config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'users/registrations',
   sessions: 'users/sessions'
 }

  resource :homes
  resources  :instructors
  resources  :students
  resources  :courses
  resources  :cohorts
  resources  :students_cohorts
  resources  :course_instructors
  root  'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students_cohorts, dependent: :destroy
  has_many :students, through: :students_cohorts, dependent: :destroy
  belongs_to :course
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
  has_many :course_instructors,  dependent: :destroy
  has_many :instructors, through: :course_instructors
end

app/models/course_instructor.rb
class CourseInstructor < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
end

app/models/create_student.rb
class CreateStudent < ApplicationRecord
  has_many :students_cohorts
  has_many :cohorts, through: :students_cohorts
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :course_instructors,  dependent: :destroy
  has_many :courses, through: :course_instructors
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :students_cohorts, dependent: :destroy
  has_many :cohorts, through: :students_cohorts

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/student_chort.rb
class StudentChort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/students_cohort.rb
class StudentsCohort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts= Cohort.all
  end

  def new
    @cohort= Cohort.new
    @courses= Course.all
  end

  def create
    Cohort.create(cohort_params)
    flash[:success] = 'Your Student has sucessfully created'
    redirect_to cohorts_path
  end

  def edit
    @cohort = Cohort.find(params[:id])
    @course = Course.find(@cohort.course_id)
    @course_all= Course.all
  end

  def update
    cohort = Cohort.find(params[:id])
    cohort.update(cohort_params)
    redirect_to cohorts_path
  end

  def destroy
    Cohort.destroy(params[:id])
    render json: {status: 'boom success', message: 'cohort was successfully deleted'}
  end

  def show
     @cohort = Cohort.find(params[:id])
  end

  private
     def cohort_params
       params.require(:cohort).permit(:name, :instructor, :start_date, :end_date, :course_id)
     end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses= Course.all
  end

  def new
    @course= Course.new
  end

  def create
    Course.create(course_params)
    flash[:success] = 'Your Student has sucessfully created'
    redirect_to courses_path
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    course = Course.find(params[:id])
    course.update(course_params)
    redirect_to courses_path
  end

  def destroy
    Course.destroy(params[:id])
    render json: {status: 'boom success', message: 'cohort was successfully deleted'}
  end

  def show
    @course = Course.find(params[:id])
  end

  private
    def course_params
       params.require(:course).permit(:course_name, :total_hours)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
   @students= Student.all
  end

  def new
   @student= Student.new
  end

  def create
   Student.create(student_params)
   flash[:success] = 'Your Student has sucessfully created'
   redirect_to students_path
  end

  def edit
   @student = Student.find(params[:id])
  end

  def update
   student = Student.find(params[:id])
   student.update(student_params)
   redirect_to students_path
  end

  def destroy
   Student.destroy(params[:id])
   render json: {status: 'boom success', message: 'student was successfully deleted'}
  end

  def show
   @student = Student.find(params[:id])
  end

  private
   def student_params
     params.require(:student).permit(:first_name, :last_name, :dob, :highest_education)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/course_instructors_helper.rb
module CourseInstructorsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/students_cohorts_helper.rb
module StudentsCohortsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/cohorts/_form.edit.html.erb
<%= render 'form.index' %>
 <div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
  <div class="container">
   <div class="row">
    <div class="col-md-6">
      <h1>  <i class="fa fa-gear"></i> New Cohort </h1>
    </div>
    </div>
  </div>
</div>
 <h2> Cohort Editorial Page</h2>
 <div class="" id="#addPostModal">
  <div class="modal-dialog modal-lg">
   <div class="modal-content">
    <div class="modal-header bg-primary text-white">
     <h5 class="modal-title">Edit Cohort Information</h5>
    </div>
    <div class="modal-body">
     <%=  form_for @cohort do |f| %>
      <div class="field form-group">
       <%= f.label :Name %>
       <%= f.text_field :name, class:"form-control"  %>
      </div>
      <div class="form-group">
       <%= f.label :Insturctor %>
       <%= f.text_field :instructor, class:"form-control"  %>
      </div>
      <div class="form-group">
       <%= f.label :Start_Date %>
       <%= f.date_field :start_date, class:"form-control" %>
      </div>
      <div class="form-group">
       <%= f.label :End_Date %>
       <%= f.date_field :end_date, class:"form-control" %>
      </div>
      <div class="form-group">
       <%= f.label :course_id, 'Select Course:' %>
       <%= f.select :course_id, options_for_select(@course_all.collect {|c| [ c.course_name, c.id ] },
       @cohort.course_id), {include_blank: 'Select Course'}%>
     </div>
   </div>
   <div class="modal-footer">
     <%= f.submit "Save", class:"btn btn-primary" %>
   </div>
   <% end %>
 </div>
</div>

app/views/cohorts/_form.footer.html.erb
<footer id="main-footer" class="bg-dark text-white mt-5 p-5">
 <div class="conatiner">
  <div class="row">
   <div class="col">
      <p class="lead text-center">Copyright &copy; 2017 Blogen</p>
   </div>
  </div>
</div>
</footer>

app/views/cohorts/_form.html.erb
<%= form_for @cohort do |f| %>
  <div>
   <%= f.label :Name %>
   <%= f.text_field :name %>
  </div>
  <div>
   <%= f.label :instructor %>
   <%= f.text_field :instructor %>
  </div>
  <div>
   <%= f.label :start_date %>
   <%= f.date_field :start_date %>
  </div>
  <div>
   <%= f.label :end_date %>
   <%= f.date_field :end_date %>
  </div>
  <div>
  </div>
  <div class="">
   <%= f.label :course_id, 'Select Course:' %><br>
   <%= f.select :course_id, options_for_select(@courses.collect {|c| [ c.course_name, c.id ] }, {include_blank: 'Select Course'})%>
  </div>
  <div>
   <%= f.submit %>
  </div>
<% end %>

app/views/cohorts/_form.index.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
 <div class="container">
  <%= link_to "Cohorts", cohorts_path, class:  "navbar-brand" %>
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
   <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item px-1 ">
        <%= link_to "Courses", courses_path, class:  "nav-link active " %>
      </li>
      <li class="nav-item px-2">
        <%= link_to "Student", students_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
        <%= link_to "Instructor", instructors_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
        <%= link_to "Student Cohort", students_cohorts_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
       <%= link_to "Course Instructor", course_instructors_path, class:  "nav-link active" %>
     </li>
   </ul>
   <ul class="navbar-nav ml-auto">
     <li class="nav-item">
       <%= link_to 'Logout',  destroy_user_session_path, method: :delete, class: " nav-link"  %>
     </li>
   </ul>
  </div>
 </div>
</nav>

app/views/cohorts/edit.html.erb
<%= render 'form.edit' %>
<%= render 'form.footer' %>

app/views/cohorts/index.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
 <div class="container">
  <div class="row">
   <div class="col-md-6">
    <h1><i class="fa fa-gear"></i> Dashboard</h1>
   </div>
  </div>
 </div>
</div>

<section id="action" class="py-4 mb-4 bg-light">
 <div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= link_to new_cohort_path,  class:"btn btn-success btn-block" do %>
       <i class="fa fa-plus"></i> New Cohort
      <% end %>
    </div>
  </div>
 </div>
</section>

<section id="posts">
 <div class="container">
  <div class="row">
   <div class="col-md-12">
    <div class="card">
     <div class="card-header">
      <h4>Cohort Lists</h4>
     </div>
     <table class="table table-hover">
      <thead>
        <tr>
         <th>#</th>
         <th>Cohort Name</th>
         <th>Course Name</th>
         <th>Instructor</th>
         <th>Start Date</th>
         <th>End Date</th>
         <th></th>
         <th></th>
         <th></th>
        </tr>
       </thead>
       <tbody>
       <% @cohorts.each_with_index do |cohort, index| %>
        <tr class="parent-tr">
         <td scope="row"><%= index+1 %></td>
         <td><%= cohort.name %></td>
         <td><%= cohort.course.course_name %></td>
         <td><%= cohort.instructor %></td>
         <td><%= cohort.start_date %></td>
         <td><%= cohort.end_date %></td>
         <td><%= link_to cohort_path(cohort), class: "btn btn-secondary" do %>
                          <h6><i class="fa fa-info"  aria-hidden="true"></i> Show </h6>
             <% end %></td>
         <td>
             <%= link_to edit_cohort_path(cohort), class: "btn btn-secondary" do %>
              <h6>  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit </h6>
             <% end %>
         </td>
         <td>
            <%= link_to  cohort, method: :delete, remote: true, class: 'delete-todo btn btn-secondary' do %>
               <h6>  <i class="fa fa-trash-o" aria-hidden="true"></i> Delete </h6>
            <% end %>

         </td>
       </tr>
      <% end %>
    </tbody>
  </table>
 </div>
</section>

<div class="modal fade" id="addUserModal">
 <div class="modal-dialog modal-lg">
  <div class="modal-content">
   <div class="modal-header bg-warning text-white">
    <h5 class="modal-title">Add User</h5>
    <button class="close" data-dismiss="modal"><span>&times;</span></button>
   </div>
   <div class="modal-body">
     <form>
       <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control">
       </div>
       <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control">
       </div>
       <div class="form-group">
        <label for="name">Password</label>
        <input type="password" class="form-control">
       </div>
       <div class="form-group">
        <label for="name">Confirm Password</label>
        <input type="password" class="form-control">
       </div>
      </form>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" data-dismiss="modal">Close</button>
      <button class="btn btn-warning" data-dismiss="modal">Save Changes</button>
    </div>
   </div>
  </div>
</div>
<%= render 'form.footer' %>

app/views/cohorts/new.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
<div class="container">
 <div class="row">
  <div class="col-md-6">
   <h1>  <i class="fa fa-plus"></i> New Cohort </h1>
  </div>
  </div>
 </div>
</div>
<h2> Cohort Insert Record</h2>

<div class="" id="#addPostModal">
 <div class="modal-dialog modal-lg">
  <div class="modal-content">
   <div class="modal-header bg-primary text-white">
    <h5 class="modal-title">Add New Cohort</h5>
   </div>
   <div class="modal-body">
    <%=  form_for @cohort do |f| %>
     <div class="field form-group">
      <%= f.label :Name %>
      <%= f.text_field :name, class:"form-control"  %>
     </div>
     <div class="form-group">
      <%= f.label :Insturctor %>
      <%= f.text_field :instructor, class:"form-control"  %>
     </div>
     <div class="form-group">
      <%= f.label :Start_Date %>
      <%= f.date_field :start_date, class:"form-control" %>
     </div>
     <div class="form-group">
      <%= f.label :End_Date %>
      <%= f.date_field :end_date, class:"form-control" %>
     </div>
     <div class="form-group">
      <%= f.label :course_id, 'Select Course:' %>
      <%= f.select :course_id, options_for_select(@courses.collect {|c| [ c.course_name, c.id ] },
            {include_blank: 'Select Course'}),  class:"form-control"%>
     </div>
   </div>
   <div class="modal-footer">
      <%= f.submit "Save", class:"btn btn-primary" %>
   </div>
    <% end %>
   </div>
 </div>
 <%= render 'form.footer' %>

app/views/cohorts/show.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
 <div class="container">
  <div class="row">
   <div class="col-md-6">
    <h1><i class="fa fa-gear"></i> Cohort </h1>
   </div>
  </div>
 </div>
</div>

<center>
 <h2> Cohort Detail Information</h2>
  <div class="card" style="width: 30rem;">
   <div class="card-body">
    <h4 class="card-title">Cohort Name</h4>
    <p class="card-text">  <%= @cohort.name %></p>
  </div>
  <div>
   <h4 class="card-title">Course Name</h4>
   <p class="card-text">  <%= @cohort.course.course_name %></p>
  </div>
  <div class="card-body">
   <h4 class="card-title">Instructor</h4>
   <p class="card-text">  <%= @cohort.instructor %></p>
  </div>
  <div class="card-body">
   <h4 class="card-title">Start Date</h4>
   <p class="card-text">  <%= @cohort.start_date %></p>
  </div>
  <div class="card-body">
   <h4 class="card-title">End Date</h4>
   <p class="card-text">  <%= @cohort.end_date %></p>
  </div>
  <div>
   <h4 class="card-title">Course Name</h4>
   <p class="card-text">  <%= @cohort.course.course_name %></p>
  </div>
  <div class="card-body">
    <%= link_to "Back to Cohorts", cohorts_path %>
  </div>
 </div>
</center>
<%= render 'form.footer' %>

app/views/students/_form.edit.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
 <div class="container">
  <div class="row">
   <div class="col-md-6">
    <h1><i class="fa fa-graduation-cap" aria-hidden="true"></i> Students</h1>
   </div>
  </div>
 </div>
</div>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
 <div>
   <%= f.label :first_name %>
   <%= f.text_field :first_name %>
 </div>
 <div>
   <%= f.label :last_name %>
   <%= f.text_field :last_name %>
 </div>
 <div>
   <%= f.label :dob %>
   <%= f.date_field :dob %>
 </div>
 <div>
   <%= f.label :highest_education %>
   <%= f.text_field :highest_education %>
 </div>
 <div>
   <%= f.submit %>
 </div>
<% end %>

app/views/students/_form.index.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
 <div class="container">
  <%= link_to "Cohorts", cohorts_path, class:  "navbar-brand" %>
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item px-2">
       <%= link_to "Courses", courses_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
       <%= link_to "Student", students_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
       <%= link_to "Instructor", instructors_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
       <%= link_to "Student Cohort", students_cohorts_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
       <%= link_to "Course Instructor", course_instructors_path, class:  "nav-link active" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
     <li class="nav-item">
       <%= link_to 'Logout',  destroy_user_session_path, method: :delete, class: " nav-link"  %>
     </li>
    </ul>
  </div>
  </div>
</nav>

app/views/students/edit.html.erb
<%= render 'form.edit' %>
<h2> Student Editorial Page</h2>
<div class="" id="#addPostModal">
 <div class="modal-dialog modal-lg">
  <div class="modal-content">
   <div class="modal-header bg-primary text-white">
    <h5 class="modal-title">Edit Student Profile</h5>
   </div>
   <div class="modal-body">
   <%= form_for @student do |f| %>
     <div class="field form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class:"form-control" %>
     </div>
     <div class="form-group">
       <%= f.label :last_name %>
       <%= f.text_field :last_name, class:"form-control" %>
     </div>
     <div class="form-group">
       <%= f.label :highest_education %>
       <%= f.text_field :highest_education, class:"form-control" %>
     </div>
     <div class="form-group">
       <%= f.label :dob %>
       <%= f.date_field :dob, class:"form-control"  %>
     </div>
    </div>
    <div class="modal-footer">
       <%= f.submit "Save", class:"btn btn-primary" %>
    </div>
  <% end %>
  </div>
 </div>
</div>

app/views/students/index.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
 <div class="container">
  <div class="row">
   <div class="col-md-6">
    <h1><i class="fa fa-graduation-cap" aria-hidden="true"></i>  Student</h1>
   </div>
  </div>
  </div>
</div>

 <!-- ACTIONS -->
<section id="action" class="py-4 mb-4 bg-light">
 <div class="container">
  <div class="row">
   <div class="col-md-3">
    <%= link_to new_student_path,  class:"btn btn-success btn-block" do %>
     <i class="fa fa-plus"></i> Create Student
    <% end %>
   </div>
  </div>
 </div>
</section>
<section id="posts">
 <div class="container">
  <div class="row">
   <div class="col-md-12">
    <div class="card">
     <div class="card-header">
      <h4>Cohort Lists</h4>
     </div>
     <table class="table table-hover">
      <thead>
       <tr>
         <th>#</th>
         <th>First Name</th>
         <th>Last Name</th>
         <th>Highest Education</th>
         <th>Date of Birth</th>
         <th></th>
         <th></th>
         <th></th>
        </tr>
       </thead>
       <tbody>
         <% @students.each_with_index do |student, index| %>
         <tr class="parent-tr">
           <td scope="row"><%= index+1 %></td>
           <td><%= student.first_name %></td>
           <td>  <%= student.last_name  %></td>
           <td>  <%= student.highest_education %></td>
           <td>  <%= student.dob %></td>
           <td>
           <%= link_to student_path(student), class: "btn btn-secondary" do %>
            <h6><i class="fa fa-info"  aria-hidden="true"></i> Show </h6>
           <% end %>
            </td>
            <td>
              <%= link_to edit_student_path(student), class: "btn btn-secondary" do %>
              <h6>  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit </h6>
              <% end %>
            </td>
            <td>
              <%= link_to  student, method: :delete, remote: true, class: 'delete-todo btn btn-secondary' do %>
              <h6>  <i class="fa fa-trash-o" aria-hidden="true"></i> Delete </h6>
              <% end %>

             </td>
          </tr>
          <% end %>
        </tbody>
      </table>
     </div>
   </section>

app/views/students/new.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
<div class="container">
 <div class="row">
  <div class="col-md-6">
   <h1>  <i class="fa fa-plus"></i> New Student </h1>
  </div>
 </div>
</div>
</div>
<h2> Student Insert Record</h2>
<div class="" id="#addPostModal">
 <div class="modal-dialog modal-lg">
  <div class="modal-content">
   <div class="modal-header bg-primary text-white">
    <h5 class="modal-title">Add New Student</h5>
   </div>
   <div class="modal-body">
    <%=  form_for @student do |f| %>
    <div class="field form-group">
     <%= f.label :first_name %>
     <%= f.text_field :first_name, class:"form-control"  %>
    </div>
    <div class="form-group">
     <%= f.label :last_name %>
     <%= f.text_field :last_name, class:"form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label :DOB %>
      <%= f.date_field :dob, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :highest_education %>
      <%= f.text_field :highest_education, class:"form-control" %>
    </div>
    <div class="modal-footer">
        <%= f.submit "Save", class:"btn btn-primary" %>
    </div>
    <% end %>
  </div>
  </div>
 </div>
</div>

app/views/students/show.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
 <div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1><i class="fa fa-graduation-cap" aria-hidden="true"></i>  Student</h1>
    </div>
  </div>
 </div>
</div>

 <center>
   <h2> Student Detail Information</h2>
   <div class="card" style="width: 30rem;">
   <div class="card-body">
     <h4 class="card-title">First Name</h4>
     <p class="card-text">  <%= @student.first_name %></p>
   </div>
   <div class="card-body">
     <h4 class="card-title">Last Name</h4>
     <p class="card-text">  <%= @student.last_name %></p>
   </div>
   <div>
     <h4 class="card-title">Highest Education</h4>
     <p class="card-text">  <%= @student.highest_education %></p>
   </div>
   <div class="card-body">
     <h4 class="card-title">Date Of Birth</h4>
     <p class="card-text">  <%= @student.dob %></p>
   </div>
   <div class="card-body">
      <%= link_to "Back to Students", students_path %>
   </div>
  </div>
 </center>