config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'users/registrations',
   sessions: 'users/sessions'
 }

  resource :homes
  resources  :instructors
  resources  :students
  resources  :courses
  resources  :cohorts
  resources  :students_cohorts
  resources  :course_instructors
  root  'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students_cohorts, dependent: :destroy
  has_many :students, through: :students_cohorts, dependent: :destroy
  belongs_to :course
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
  has_many :course_instructors,  dependent: :destroy
  has_many :instructors, through: :course_instructors
end

app/models/course_instructor.rb
class CourseInstructor < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
end

app/models/create_student.rb
class CreateStudent < ApplicationRecord
  has_many :students_cohorts
  has_many :cohorts, through: :students_cohorts
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :course_instructors,  dependent: :destroy
  has_many :courses, through: :course_instructors
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :students_cohorts, dependent: :destroy
  has_many :cohorts, through: :students_cohorts

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/student_chort.rb
class StudentChort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/students_cohort.rb
class StudentsCohort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts= Cohort.all
  end

  def new
    @cohort= Cohort.new
    @courses= Course.all
  end

  def create
    Cohort.create(cohort_params)
    flash[:success] = 'Your Student has sucessfully created'
    redirect_to cohorts_path
  end

  def edit
    @cohort = Cohort.find(params[:id])
    @course = Course.find(@cohort.course_id)
    @course_all= Course.all
  end

  def update
    cohort = Cohort.find(params[:id])
    cohort.update(cohort_params)
    redirect_to cohorts_path
  end

  def destroy
    Cohort.destroy(params[:id])
    render json: {status: 'boom success', message: 'cohort was successfully deleted'}
  end

  def show
     @cohort = Cohort.find(params[:id])
  end

  private
     def cohort_params
       params.require(:cohort).permit(:name, :instructor, :start_date, :end_date, :course_id)
     end
end

app/controllers/course_instructors_controller.rb
class CourseInstructorsController < ApplicationController

  def index
    @course_instructors = CourseInstructor.all
  end

  def new
    @course_instructor= CourseInstructor.new
    @courses= Course.all
    @instructors = Instructor.all
  end

  def create
    CourseInstructor.create(course_instructors_params)
    flash[:success] = 'Your Student has sucessfully created'
    redirect_to course_instructors_path
  end

  def edit
    @course_instructor = CourseInstructor.find(params[:id])
    @courses= Course.all
    @instructors = Instructor.all
  end

  def update
    courseinstructor = CourseInstructor.find(params[:id])
    courseinstructor.update(course_instructors_params)
    redirect_to  course_instructors_path
  end

  def show
     @courseinstructor = CourseInstructor.find(params[:id])
  end

  def destroy
    CourseInstructor.destroy(params[:id])
    render json: {status: 'boom success', message: 'student was successfully deleted'}
  end

  private
    def course_instructors_params
        params.require(:course_instructor).permit(:course_id, :instructor_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses= Course.all
  end

  def new
    @course= Course.new
  end

  def create
    Course.create(course_params)
    flash[:success] = 'Your Student has sucessfully created'
    redirect_to courses_path
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    course = Course.find(params[:id])
    course.update(course_params)
    redirect_to courses_path
  end

  def destroy
    Course.destroy(params[:id])
    render json: {status: 'boom success', message: 'cohort was successfully deleted'}
  end

  def show
    @course = Course.find(params[:id])
  end

  private
    def course_params
       params.require(:course).permit(:course_name, :total_hours)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
   @students= Student.all
  end

  def new
   @student= Student.new
  end

  def create
   Student.create(student_params)
   flash[:success] = 'Your Student has sucessfully created'
   redirect_to students_path
  end

  def edit
   @student = Student.find(params[:id])
  end

  def update
   student = Student.find(params[:id])
   student.update(student_params)
   redirect_to students_path
  end

  def destroy
   Student.destroy(params[:id])
   render json: {status: 'boom success', message: 'student was successfully deleted'}
  end

  def show
   @student = Student.find(params[:id])
  end

  private
   def student_params
     params.require(:student).permit(:first_name, :last_name, :dob, :highest_education)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/course_instructors_helper.rb
module CourseInstructorsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/students_cohorts_helper.rb
module StudentsCohortsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/course_instructors/_form.index.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
  <div class="container">
    <!-- <a href="index.html" class="navbar-brand">Cohorts</a> -->
    <%= link_to "Cohorts", cohorts_path, class:  "navbar-brand" %>



    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item px-2">
            <%= link_to "Courses", courses_path, class:  "nav-link active" %>
          <!-- <a href="index.html" class="nav-link active">Courses</a> -->
        </li>
        <li class="nav-item px-2">
          <%= link_to "Student", students_path, class:  "nav-link active" %>
          <!-- <a href="posts.html" class="nav-link">Students</a> -->
        </li>
        <li class="nav-item px-2">

          <%= link_to "Instructor", instructors_path, class:  "nav-link active" %>
        </li>
        <li class="nav-item px-2">
          <%= link_to "Student Cohort", students_cohorts_path, class:  "nav-link active" %>

        </li>
        <li class="nav-item px-2">
          <%= link_to "Course Instructor", course_instructors_path, class:  "nav-link active" %>

        </li>

      </ul>

      <ul class="navbar-nav ml-auto">
  
        <li class="nav-item">
           <%= link_to 'Logout',  destroy_user_session_path, method: :delete, class: " nav-link"  %>


        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/course_instructors/edit.html.erb
<%= render 'form.edit' %>
<h2> Course Editorial Page</h2>

<div class="" id="#addPostModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-primary text-white">
        <h5 class="modal-title">Edit Course Profile</h5>
      </div>
      <!-- <div class="modal-body"> -->
      <div class="modal-body">

    <%= form_for @course_instructor do |f| %>


              <div class="form-group">
                 <%= f.label :course_name, 'Select Course:' %>
                 
                     <%= f.select :course_id, options_for_select(@courses.collect {|c| [ c.course_name,
                                                                 c.id ] },
                         @course_instructor.course_id), {include_blank: 'Select Course'}, class:"form-control" %>

              </div>
              <div class="form-group">

                 <%= f.label :instructor_name, 'Select Instructor:' %>
                 <%= f.select :instructor_id, options_for_select(@instructors.collect {|c| [ c.first_name,
                                                             c.id ] },
                     @course_instructor.instructor_id), {include_blank: 'Select Instructor'}, class:"form-control"%>

              </div>
           </div>
        <div class="modal-footer">

                  <%= f.submit "Save", class:"btn btn-primary" %>
            </div>
       <% end %>
    </div>
</div>

</div>

app/views/course_instructors/index.html.erb
<%= render 'form.index' %>
 <div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1><i class="fa fa-graduation-cap" aria-hidden="true"></i>  Course Instructor</h1>
        </div>
      </div>
    </div>
  </div>

  <!-- ACTIONS -->


<section id="action" class="py-4 mb-4 bg-light">
  <div class="container">
    <div class="row">

      <div class="col-md-3">
        <%= link_to new_course_instructor_path,  class:"btn btn-success btn-block" do %>
          <i class="fa fa-plus"></i> Create Course Instructor
        <% end %>
      </div>

    </div>
  </div>
</section>


<!-- POSTS -->
<section id="posts">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h4>Course Instructor</h4>
          </div>
          <!-- <table class="table table-striped"> -->

          <table class="table table-hover">
            <!-- <thead class="thead-inverse"> -->

             <thead>
              <tr class="parent-tr">
                <th>#</th>
                <th>Course Name</th>
                <th>Total hours</th>
                <th>Instructor First Name</th>
                <th>Instructor Lirst Name</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
                <% @course_instructors.each_with_index do |course_instructor, index| %>
                <tr class="parent-tr">

                <td scope="row"><%= index+1 %></td>
                <td><%= course_instructor.course.course_name %></td>
                <td>  <%= course_instructor.course.total_hours %></td>
                <td>  <%= course_instructor.instructor.first_name %></td>
                <td>  <%= course_instructor.instructor.first_name %></td>


                <td>
                   <%= link_to course_instructor_path(course_instructor), class: "btn btn-secondary" do %>
                        <h6><i class="fa fa-info"  aria-hidden="true"></i> Show </h6>

                  <% end %>
                
                </td>

                 <td>
                  <%= link_to edit_course_instructor_path(course_instructor), class: "btn btn-secondary" do %>
                      <h6>  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit </h6>
                  <% end %>

                  </td>
                  <td>

                   <%= link_to course_instructor, method: :delete, remote: true, class: 'delete-todo btn btn-secondary' do %>
                   <h6>  <i class="fa fa-trash-o" aria-hidden="true"></i> Delete </h6>
                   <% end %>
                  </td>
              </tr>
              <% end %>


            </tbody>
          </table>
        </div>

</section>

app/views/course_instructors/new.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
 <div class="container">
  <div class="row">
   <div class="col-md-6">
    <h1>  <i class="fa fa-plus"></i> New Course Instructor </h1>
   </div>
  </div>
 </div>
</div>
<h2> Course Instructor Insert Record</h2>
<div class="" id="#addPostModal">
 <div class="modal-dialog modal-lg">
  <div class="modal-content">
   <div class="modal-header bg-primary text-white">
    <h5 class="modal-title">Add New Course Instructor</h5>
   </div>
   <div class="modal-body">
    <%= form_for @course_instructor do |f| %>
    <div class="field form-group">
     <%= f.label :course_id, 'Select Course:' %><br>
     <%= f.select :course_id, options_for_select(@courses.collect {|c| [ c.course_name, c.id ] }, {include_blank: 'Select Course'})%>
    </div>
    <div class="field form-group">
     <%= f.label :instructor_id, 'Select Instructor:' %><br>
     <%= f.select :instructor_id, options_for_select(@instructors.collect {|c| [ c.first_name, c.id ] }, {include_blank: 'Select Instructor'})%>
    </div>
    <div class="modal-footer">
     <%= f.submit "Save", class:"btn btn-primary" %>
    </div>
   <% end %>
  </div>
  </div>
 </div>
</div>