config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'users/registrations',
   sessions: 'users/sessions'
 }

  resource :homes
  resources  :instructors
  resources  :students
  resources  :courses
  resources  :cohorts
  resources  :students_cohorts
  resources  :course_instructors
  root  'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students_cohorts, dependent: :destroy
  has_many :students, through: :students_cohorts, dependent: :destroy
  belongs_to :course
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
  has_many :course_instructors,  dependent: :destroy
  has_many :instructors, through: :course_instructors
end

app/models/course_instructor.rb
class CourseInstructor < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
end

app/models/create_student.rb
class CreateStudent < ApplicationRecord
  has_many :students_cohorts
  has_many :cohorts, through: :students_cohorts
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :course_instructors,  dependent: :destroy
  has_many :courses, through: :course_instructors
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :students_cohorts, dependent: :destroy
  has_many :cohorts, through: :students_cohorts

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/student_chort.rb
class StudentChort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/students_cohort.rb
class StudentsCohort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts= Cohort.all
  end

  def new
    @cohort= Cohort.new
    @courses= Course.all
  end

  def create
    Cohort.create(cohort_params)
    flash[:success] = 'Your Student has sucessfully created'
    redirect_to cohorts_path
  end

  def edit
    @cohort = Cohort.find(params[:id])
    @course = Course.find(@cohort.course_id)
    @course_all= Course.all
  end

  def update
    cohort = Cohort.find(params[:id])
    cohort.update(cohort_params)
    redirect_to cohorts_path
  end

  def destroy
    Cohort.destroy(params[:id])
    render json: {status: 'boom success', message: 'cohort was successfully deleted'}
  end

  def show
     @cohort = Cohort.find(params[:id])
  end

  private
     def cohort_params
       params.require(:cohort).permit(:name, :instructor, :start_date, :end_date, :course_id)
     end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses= Course.all
  end

  def new
    @course= Course.new
  end

  def create
    Course.create(course_params)
    flash[:success] = 'Your Student has sucessfully created'
    redirect_to courses_path
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    course = Course.find(params[:id])
    course.update(course_params)
    redirect_to courses_path
  end

  def destroy
    Course.destroy(params[:id])
    render json: {status: 'boom success', message: 'cohort was successfully deleted'}
  end

  def show
    @course = Course.find(params[:id])
  end

  private
    def course_params
       params.require(:course).permit(:course_name, :total_hours)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
   @students= Student.all
  end

  def new
   @student= Student.new
  end

  def create
   Student.create(student_params)
   flash[:success] = 'Your Student has sucessfully created'
   redirect_to students_path
  end

  def edit
   @student = Student.find(params[:id])
  end

  def update
   student = Student.find(params[:id])
   student.update(student_params)
   redirect_to students_path
  end

  def destroy
   Student.destroy(params[:id])
   render json: {status: 'boom success', message: 'student was successfully deleted'}
  end

  def show
   @student = Student.find(params[:id])
  end

  private
   def student_params
     params.require(:student).permit(:first_name, :last_name, :dob, :highest_education)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/course_instructors_helper.rb
module CourseInstructorsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/students_cohorts_helper.rb
module StudentsCohortsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.edit.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
 <div class="container">
  <div class="row">
   <div class="col-md-6">
    <h1><i class="fa fa-graduation-cap" aria-hidden="true"></i> Course</h1>
   </div>
  </div>
 </div>
</div>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
 <div>
   <%= f.label :course_name %>
   <%= f.text_field :course_name %>
 </div>
 <div>
   <%= f.label :total_hours %>
   <%= f.text_field :total_hours %>
 </div>
 <div>
   <%= f.submit %>
 </div>
<% end %>

app/views/courses/_form.index.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
 <div class="container">
  <%= link_to "Cohorts", cohorts_path, class:  "navbar-brand" %>
   <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
     <span class="navbar-toggler-icon"></span>
   </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item px-2">
        <%= link_to "Courses", courses_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
       <%= link_to "Student", students_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
       <%= link_to "Instructor", instructors_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
       <%= link_to "Student Cohort", students_cohorts_path, class:  "nav-link active" %>
      </li>
      <li class="nav-item px-2">
       <%= link_to "Course Instructor", course_instructors_path, class:  "nav-link active" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
       <%= link_to 'Logout',  destroy_user_session_path, method: :delete, class: " nav-link"  %>
      </li>
    </ul>
  </div>
 </div>
</nav>

app/views/courses/edit.html.erb
<%= render 'form.edit' %>
<h2> Course Editorial Page</h2>
<div class="" id="#addPostModal">
 <div class="modal-dialog modal-lg">
  <div class="modal-content">
   <div class="modal-header bg-primary text-white">
    <h5 class="modal-title">Edit Course Profile</h5>
   </div>
   <div class="modal-body">
    <%=  form_for @course do |f| %>
     <div class="field form-group">
      <%= f.label :course_name %>
      <%= f.text_field :course_name, class:"form-control"  %>
     </div>
     <div class="form-group">
      <%= f.label :total_hours %>
      <%= f.text_field :total_hours, class:"form-control"  %>
     </div>
   </div>
   <div class="modal-footer">
    <%= f.submit "Save", class:"btn btn-primary" %>
   </div>
  <% end %>
  </div>
 </div>
</div>

app/views/courses/index.html.erb
<%= render 'form.index' %>
<div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
 <div class="container">
  <div class="row">
   <div class="col-md-6">
    <h1><i class="fa fa-graduation-cap" aria-hidden="true"></i>  Course</h1>
   </div>
  </div>
 </div>
</div>
<section id="action" class="py-4 mb-4 bg-light">
 <div class="container">
  <div class="row">
   <div class="col-md-3">
    <%= link_to new_course_path,  class:"btn btn-success btn-block" do %>
     <i class="fa fa-plus"></i> Create Course
    <% end %>
   </div>
  </div>
 </div>
</section>

<section id="posts">
 <div class="container">
  <div class="row">
   <div class="col-md-12">
    <div class="card">
     <div class="card-header">
      <h4>Course Lists</h4>
     </div>
     <table class="table table-hover">
       <thead>
        <tr>
         <th>#</th>
         <th>Course Name</th>
         <th>Total Hours</th>
         <th></th>
         <th></th>
         <th></th>
        </tr>
      </thead>
      <tbody>
        <% @courses.each_with_index  do |course, index| %>
         <tr class="parent-tr">
          <td scope="row"><%= index+1 %></td>
          <td><%= course.course_name %></td>
          <td>  <%= course.total_hours %></td>
          <td>
             <%= link_to course_path(course), class: "btn btn-secondary" do %>
                <h6><i class="fa fa-info"  aria-hidden="true"></i> Show </h6>
             <% end %>
          </td>
           <td>
             <%= link_to edit_course_path(course), class: "btn btn-secondary" do %>
                    <h6>  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit </h6>
             <% end %>
           </td>
           <td>
              <%= link_to  course, method: :delete, remote: true, class: 'delete-todo btn btn-secondary' do %>
              <h6>  <i class="fa fa-trash-o" aria-hidden="true"></i> Delete </h6>
             <% end %>
           </td>
          </tr>
        <% end %>
       </tbody>
      </table>
    </div>
 </section>

app/views/courses/new.html.erb
<h3> Create a New Student  </h3>
<%= render 'form' %>

app/views/courses/show.html.erb
<%= render 'form.index' %>
 <div class="backend_header" id="main-header" class="py-2 bg-primary text-white">
  <div class="container">
   <div class="row">
    <div class="col-md-6">
     <h1><i class="fa fa-graduation-cap" aria-hidden="true"></i> Course</h1>
    </div>
   </div>
  </div>
 </div>

<center>
  <h2> Course Detail Information</h2>
 <div class="card" style="width: 30rem;">
  <div class="card-body">
    <h4 class="card-title">Course Name</h4>
    <p class="card-text">  <%= @course.course_name %></p>
  </div>
  <div>
    <h4 class="card-title">Total Hours</h4>
    <p class="card-text">  <%= @course.total_hours %></p>
  </div>
  <div class="card-body">
    <%= link_to "Back to Courses", courses_path %>
  </div>
 </div>
</center>

app/views/homes/index.html.erb
<title>Student Profile</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<body>
 <header>
   <nav>
    <div class="row">
     <ul class="main-nav js--main-nav">
      <li><%= link_to 'Sign Up', new_user_registration_path %></a></li>
      <li><%= link_to 'Log In', new_user_session_path %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %> </li>
     </ul>
    </div>
    </nav>
    <div class="hero-text-box">
     <h1> NYCDA Student Profile  </h1>
    </div>
 </header>